WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_gemini_opt_0203.py", line 482, in <module>
  File "train_gemini_opt_0203.py", line 482, in <module>
Traceback (most recent call last):
  File "train_gemini_opt_0203.py", line 482, in <module>
    main()
  File "train_gemini_opt_0203.py", line 282, in main
    main()
  File "train_gemini_opt_0203.py", line 282, in main
    colossalai.launch_from_torch({})
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/initialize.py", line 220, in launch_from_torch
    colossalai.launch_from_torch({})
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/initialize.py", line 220, in launch_from_torch
    main()
  File "train_gemini_opt_0203.py", line 282, in main
    launch(config=config,
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/initialize.py", line 108, in launch
    gpc.set_device(local_rank)
      File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/context/parallel_context.py", line 519, in set_device
launch(config=config,
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/initialize.py", line 108, in launch
    gpc.set_device(local_rank)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/context/parallel_context.py", line 519, in set_device
        colossalai.launch_from_torch({})torch.cuda.set_device(device_ordinal)

  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in set_device
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/initialize.py", line 220, in launch_from_torch
    torch.cuda.set_device(device_ordinal)    
torch._C._cuda_setDevice(device)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in set_device
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    launch(config=config,
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/initialize.py", line 108, in launch
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    gpc.set_device(local_rank)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/context/parallel_context.py", line 519, in set_device
    torch.cuda.set_device(device_ordinal)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[02/13/23 15:56:44] INFO     colossalai - colossalai - INFO: /root/anaconda3/envs/py38/lib/python3.8/site-packages/colossalai/context/parallel_context.py:521   
                             set_device                                                                                                                         
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0                                                                
